#!/usr/bin/env python3
"""
Patches android/app/src/main/AndroidManifest.xml (generated by `flutter create .`)
so the app can:
  1. Use the network at all (INTERNET permission).
  2. Talk to 9Router over plain http://localhost — cleartext traffic is
     blocked by default on Android 9+, so we point it at the
     network_security_config.xml that only allows cleartext to loopback
     addresses.

Safe to run multiple times — it checks before inserting anything.
"""
import re
import sys
from pathlib import Path

MANIFEST_PATH = Path("android/app/src/main/AndroidManifest.xml")


def main() -> int:
    if not MANIFEST_PATH.exists():
        print(f"Could not find {MANIFEST_PATH}.")
        print("Run `flutter create .` first (from the project root), then re-run this script.")
        return 1

    text = MANIFEST_PATH.read_text(encoding="utf-8")
    original = text

    # 1. Ensure the INTERNET permission is present.
    if "android.permission.INTERNET" not in text:
        text = re.sub(
            r"(<manifest[^>]*>)",
            r'\1\n    <uses-permission android:name="android.permission.INTERNET" />',
            text,
            count=1,
        )
        print("Added INTERNET permission.")
    else:
        print("INTERNET permission already present.")

    # 2. Ensure the <application> tag references our network security config
    #    and allows cleartext traffic.
    app_tag_match = re.search(r"<application\b[^>]*>", text)
    if not app_tag_match:
        print("Could not find <application> tag — please check the manifest manually.")
        return 1

    app_tag = app_tag_match.group(0)
    new_app_tag = app_tag

    if "android:networkSecurityConfig" not in new_app_tag:
        new_app_tag = new_app_tag.replace(
            "<application",
            '<application\n        android:networkSecurityConfig="@xml/network_security_config"',
            1,
        )
        print("Added android:networkSecurityConfig attribute.")
    else:
        print("android:networkSecurityConfig already present.")

    if "android:usesCleartextTraffic" not in new_app_tag:
        new_app_tag = new_app_tag.replace(
            "<application",
            '<application\n        android:usesCleartextTraffic="true"',
            1,
        )
        print("Added android:usesCleartextTraffic attribute.")
    else:
        print("android:usesCleartextTraffic already present.")

    text = text.replace(app_tag, new_app_tag, 1)

    if text != original:
        MANIFEST_PATH.write_text(text, encoding="utf-8")
        print(f"\nUpdated {MANIFEST_PATH}.")
    else:
        print("\nNothing to change — manifest already patched.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
